services:

  # ----- /!\ -----
  # --- DEV ONLY ---
  # ----- /!\ -----

  # This setup uses environment variables.
  # The command `make setup` will `cp .env.example .env`.
  # You can then edit this newly created `.env` if needed.

  reverse_proxy:
    build:
      context: ./infrastructure/reverse_proxy
      target: dev
    privileged: true
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front_network
    depends_on:
      platform:
        condition: service_healthy
      archive:
        condition: service_healthy
      frontend:
        condition: service_healthy

  database:
    build:
      context: ./infrastructure/database/postgres
      target: dev
    environment:
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_NAME: ${DB_NAME}
      DB_ADMIN: ${DB_ADMIN}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - database_network

  test_database:
    build:
      context: ./infrastructure/database/postgres
      target: dev
    environment:
      POSTGRES_USER: testdbadmin
      POSTGRES_PASSWORD: testdbadmin
      POSTGRES_DB: testdb
      DB_NAME: testdb
      DB_ADMIN: testdbadmin
      DB_ADMIN_PASSWORD: testdbadmin
      DB_USER: testdbuser
      DB_USER_PASSWORD: testdbuser
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - database_network

  # migrator:
  #   build: ./infrastructure/database/migrator
  #   privileged: true
  #   environment:
  #     - DATABASE_URL=postgres://${DB_ADMIN}:${DB_ADMIN_PASSWORD}@${DB_HOST}/${DB_NAME}?sslmode=disable
  #     - DBMATE_MIGRATIONS_DIR=${MIGRATOR_MIGRATIONS_DIR}
  #   volumes:
  #     - ./infrastructure/database/migrator/migrations:/app/${MIGRATOR_MIGRATIONS_DIR}
  #   networks:
  #     - database_network
  #   depends_on:
  #     database:
  #       condition: service_healthy

  platform:
    build:
      context: ./services/platform
      target: dev
    restart: unless-stopped
    environment:
      MIX_ENV: ${PLATFORM_ENV}
      SECRET_KEY_BASE: ${PLATFORM_SECRET_KEY_BASE}
      DATABASE_URL: ecto://${DB_USER}:${DB_USER_PASSWORD}@${DB_HOST}/${DB_NAME}
      POOL_SIZE_OUTBOX: ${DB_POOL_SIZE_OUTBOX}
      POOL_SIZE_IAM: ${DB_POOL_SIZE_IAM}
      POOL_SIZE_ROLEPLAY: ${DB_POOL_SIZE_ROLEPLAY}
      POOL_SIZE_SOCIAL: ${DB_POOL_SIZE_SOCIAL}
      POOL_SIZE_SOVEREIGNTY: ${DB_POOL_SIZE_SOVEREIGNTY}
      PHX_SERVER: ${PLATFORM_PHX_SERVER}
      PHX_HOST: ${PLATFORM_PHX_HOST}
      PORT: ${PLATFORM_PORT}
      DOCKER: ${DOCKER}
      CORS_ORIGINS: ${PLATFORM_CORS_ORIGINS}
    ports:
      - "4000:4000"
    volumes:
      - ./services/platform:/app:rw,cached,z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform.rule=Host(`platform.localhost`)"
      - "traefik.http.services.platform.loadbalancer.server.port=4000"
      - "traefik.docker.network=${PROJECT_NAME}_front_network"
    networks:
      - front_network
      - database_network
    depends_on:
      database:
        condition: service_healthy

  archive:
    build:
      context: ./services/archive
      target: dev
    restart: unless-stopped
    environment:
      APP_ENV: ${ARCHIVE_ENV}
      APP_SECRET: ${ARCHIVE_SECRET}
    volumes:
      - ./services/archive:/app:rw,cached,z
      - /app/var
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.archive.rule=Host(`archive.localhost`)"
      - "traefik.http.services.archive.loadbalancer.server.port=9000"
      - "traefik.docker.network=${PROJECT_NAME}_front_network"
    networks:
      - front_network

  frontend:
    build:
      context: ./services/frontend
      target: dev
    restart: unless-stopped
    environment:
      NODE_ENV: ${FRONTEND_ENV}
      PUBLIC_PLATFORM_URL: ${FRONTEND_PUBLIC_PLATFORM_URL}
      PUBLIC_ARCHIVE_URL: ${FRONTEND_PUBLIC_ARCHIVE_URL}
      PLATFORM_URL_INTERNAL: ${FRONTEND_PLATFORM_URL_INTERNAL}
      ARCHIVE_URL_INTERNAL: ${FRONTEND_ARCHIVE_URL_INTERNAL}
    volumes:
      - ./services/frontend:/app:rw,cached,z
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=${PROJECT_NAME}_front_network"
    networks:
      - front_network
    depends_on:
      platform:
        condition: service_healthy
      archive:
        condition: service_started

volumes:
  db-data:

networks:
  front_network:
    driver: bridge
  database_network:
    driver: bridge
