// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type OutboxMessageStatus string

const (
	OutboxMessageStatusPending OutboxMessageStatus = "pending"
	OutboxMessageStatusSuccess OutboxMessageStatus = "success"
	OutboxMessageStatusFailed  OutboxMessageStatus = "failed"
)

func (e *OutboxMessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxMessageStatus(s)
	case string:
		*e = OutboxMessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxMessageStatus: %T", src)
	}
	return nil
}

type NullOutboxMessageStatus struct {
	OutboxMessageStatus OutboxMessageStatus
	Valid               bool // Valid is true if OutboxMessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxMessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxMessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxMessageStatus), nil
}

type PlatformThemeEnum string

const (
	PlatformThemeEnumDark  PlatformThemeEnum = "dark"
	PlatformThemeEnumLight PlatformThemeEnum = "light"
)

func (e *PlatformThemeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformThemeEnum(s)
	case string:
		*e = PlatformThemeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformThemeEnum: %T", src)
	}
	return nil
}

type NullPlatformThemeEnum struct {
	PlatformThemeEnum PlatformThemeEnum
	Valid             bool // Valid is true if PlatformThemeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformThemeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformThemeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformThemeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformThemeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformThemeEnum), nil
}

type UserRoleEnum string

const (
	UserRoleEnumUser    UserRoleEnum = "user"
	UserRoleEnumCurator UserRoleEnum = "curator"
	UserRoleEnumAdmin   UserRoleEnum = "admin"
)

func (e *UserRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleEnum(s)
	case string:
		*e = UserRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleEnum: %T", src)
	}
	return nil
}

type NullUserRoleEnum struct {
	UserRoleEnum UserRoleEnum
	Valid        bool // Valid is true if UserRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleEnum), nil
}

type Battle struct {
	ID                   string
	AttackerKingdomID    uuid.NullUUID
	DefenderKingdomID    uuid.NullUUID
	AttackerInitialTroop []int32
	DefenderInitialTroop []int32
	Log                  json.RawMessage
	AttackerFinalTroop   []int32
	DefenderFinalTroop   []int32
	AttackerWins         bool
	AttackerFameModifier string
	DefenderFameModifier string
	InsertedAt           time.Time
}

type Board struct {
	ID          string
	UserID      string
	Title       string
	Description string
	Slug        string
	IsArchived  bool
	IsRemoved   bool
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type Chapter struct {
	ID            string
	ChronicleID   string
	ProtagonistID string
	Content       string
	InsertedAt    time.Time
	UpdatedAt     time.Time
}

type ChaptersView struct {
	ChapterID  string
	UserID     string
	InsertedAt time.Time
}

type Chronicle struct {
	ID string
	// User mastering the chronicle
	NarratorID  string
	PlayerID    string
	Title       string
	Slug        string
	Description sql.NullString
	IsArchived  bool
	IsRemoved   bool
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type IamSession struct {
	ID         string
	UserID     string
	Token      []byte
	Context    string
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	ExpiresAt  time.Time
	InsertedAt time.Time
}

type IamUser struct {
	ID             string
	Nickname       string
	Email          string
	ProfilePicture sql.NullString
	Password       string
	Slug           string
	Roles          []UserRoleEnum
	PlatformTheme  PlatformThemeEnum
	IsEnabled      bool
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

type Kingdom struct {
	ID       string
	PlayerID string
	// Protagonist leading the kingdom
	LeaderID     string
	Name         string
	Slug         string
	Fame         string
	DefenseTroop []int32
	AttackTroop  []int32
	// One active kingdom per user a time
	IsActive   bool
	IsRemoved  bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type Missife struct {
	ID string
	// Kingdom sending the missive
	SenderID string
	// Kingdom receiving the missive
	ReceiverID string
	Content    string
	IsRead     bool
	InsertedAt time.Time
}

// Technical table – asynchronous message bus
type Outbox struct {
	ID int32
	// Message’s identifier – example: “UserRegistered”
	MessageType string
	// Message’s payload
	Payload  json.RawMessage
	Metadata pqtype.NullRawMessage
	// List of the services which have already consumed the message
	ConsumedBy     []string
	FailedAttempts int32
	LastError      sql.NullString
	Status         OutboxMessageStatus
	// Time of the dispatch start
	ScheduledAt time.Time
	// Time of the the last consumption, sealing the message
	ClosedAt sql.NullTime
}

type Post struct {
	ID         string
	UserID     string
	TopicID    string
	Content    string
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type Protagonist struct {
	ID             string
	PlayerID       string
	KingdomID      uuid.NullUUID
	Name           string
	Fame           string
	Slug           string
	IsAnonymous    bool
	ProfilePicture sql.NullString
	Biography      sql.NullString
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

type ProtagonistsChronicle struct {
	ProtagonistID string
	ChronicleID   string
}

type RoleplayChapter struct {
	ID            string
	ChronicleID   string
	ProtagonistID string
	Content       string
	InsertedAt    time.Time
	UpdatedAt     time.Time
}

type RoleplayChronicle struct {
	ID          string
	NarratorID  string
	PlayerID    string
	Title       string
	Slug        string
	Description sql.NullString
	IsArchived  bool
	IsRemoved   bool
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type RoleplayKingdom struct {
	ID   string
	Name string
	Fame string
	Slug string
}

type RoleplayPlayer struct {
	ID             string
	Nickname       string
	ProfilePicture sql.NullString
	Slug           string
}

type RoleplayProtagonist struct {
	ID             string
	PlayerID       string
	KingdomID      uuid.NullUUID
	Name           string
	Fame           string
	Slug           string
	IsAnonymous    bool
	ProfilePicture sql.NullString
	Biography      sql.NullString
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

type RoleplayWhisper struct {
	ID         string
	Content    sql.NullString
	SenderID   string
	ReceiverID string
	IsRead     bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type Session struct {
	ID         string
	UserID     string
	Token      []byte
	Context    string
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	ExpiresAt  time.Time
	InsertedAt time.Time
}

// Chat messages between users (only one general channel)
type Shout struct {
	ID         string
	UserID     string
	Content    sql.NullString
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type SocialBoard struct {
	ID          string
	UserID      string
	Title       string
	Description string
	Slug        string
	IsArchived  bool
	IsRemoved   bool
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type SocialPost struct {
	ID         string
	UserID     string
	TopicID    string
	Content    string
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type SocialShout struct {
	ID         string
	UserID     string
	Content    sql.NullString
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type SocialTopic struct {
	ID         string
	UserID     string
	BoardID    string
	Title      string
	Slug       string
	IsRemoved  bool
	IsArchived bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type SocialUser struct {
	ID             string
	Nickname       string
	Email          string
	ProfilePicture sql.NullString
	Password       string
	Slug           string
	Roles          []UserRoleEnum
	PlatformTheme  PlatformThemeEnum
	IsEnabled      bool
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

type SovereigntyBattle struct {
	ID                   string
	AttackerKingdomID    uuid.NullUUID
	DefenderKingdomID    uuid.NullUUID
	AttackerInitialTroop []int32
	DefenderInitialTroop []int32
	Log                  json.RawMessage
	AttackerFinalTroop   []int32
	DefenderFinalTroop   []int32
	AttackerWins         bool
	AttackerFameModifier string
	DefenderFameModifier string
	InsertedAt           time.Time
}

type SovereigntyKingdom struct {
	ID           string
	PlayerID     string
	LeaderID     string
	Name         string
	Slug         string
	Fame         string
	DefenseTroop []int32
	AttackTroop  []int32
	IsActive     bool
	IsRemoved    bool
	InsertedAt   time.Time
	UpdatedAt    time.Time
}

type SovereigntyMissife struct {
	ID         string
	SenderID   string
	ReceiverID string
	Content    string
	IsRead     bool
	InsertedAt time.Time
}

type SovereigntyNotable struct {
	ID             string
	PlayerID       string
	KingdomID      uuid.NullUUID
	Name           string
	Fame           string
	Slug           string
	IsAnonymous    bool
	ProfilePicture sql.NullString
	Biography      sql.NullString
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

type SovereigntyPlayer struct {
	ID             string
	Nickname       string
	ProfilePicture sql.NullString
	Slug           string
}

type TechnicalOutbox struct {
	ID             int32
	MessageType    string
	Payload        json.RawMessage
	Metadata       pqtype.NullRawMessage
	ConsumedBy     []string
	FailedAttempts int32
	LastError      sql.NullString
	Status         OutboxMessageStatus
	ScheduledAt    time.Time
	ClosedAt       sql.NullTime
}

type Topic struct {
	ID         string
	UserID     string
	BoardID    string
	Title      string
	Slug       string
	IsRemoved  bool
	IsArchived bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             string
	Nickname       string
	Email          string
	ProfilePicture sql.NullString
	Password       string
	Slug           string
	Roles          []UserRoleEnum
	PlatformTheme  PlatformThemeEnum
	IsEnabled      bool
	IsRemoved      bool
	InsertedAt     time.Time
	UpdatedAt      time.Time
}

// Private messages between two protagonists
type Whisper struct {
	ID      string
	Content sql.NullString
	// Protagonist sending the whisper
	SenderID string
	// Protagonist receiving the whisper
	ReceiverID string
	IsRead     bool
	InsertedAt time.Time
	UpdatedAt  time.Time
}
