// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO iam.users (
	id, nickname, email, password, slug, roles, platform_theme
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserParams struct {
	ID            string
	Nickname      string
	Email         string
	Password      string
	Slug          string
	Roles         []UserRoleEnum
	PlatformTheme PlatformThemeEnum
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Nickname,
		arg.Email,
		arg.Password,
		arg.Slug,
		pq.Array(arg.Roles),
		arg.PlatformTheme,
	)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, nickname, email, profile_picture, password, slug, roles, platform_theme, is_enabled, is_removed, inserted_at, updated_at
FROM iam.users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (IamUser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.ProfilePicture,
		&i.Password,
		&i.Slug,
		pq.Array(&i.Roles),
		&i.PlatformTheme,
		&i.IsEnabled,
		&i.IsRemoved,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
